print()
print("welcome".center(60))
print()
x=int(input('enter x'))
y=int(input('enter y'))
print()
print(f" x={x}".center(60).rstrip())
print()
print(f" y={y}".center(60).rstrip())
print()
print(f"{x}+{y} ={x+y}".center(60))
print()
print("thanks".center(60))
